from . import portal_privilege
from . import federation_club_role_type
from . import federation_club_representative
from . import federation_club
from . import federation_team
from . import federation_tournament
from . import res_partner
from . import res_users
from . import federation_tournament_registration
from . import federation_season_registration
from . import federation_referee
from . import federation_match_referee
from . import federation_team_roster
from . import federation_match_sheet
from . import federation_player
