{
    "name": "Sports Federation Notifications",
    "version": "19.0.1.2.0",
    "category": "Sports",
    "summary": "Centralized federation notification helpers, templates, and scheduled reminders",
    "description": "Notification templates, reminder jobs, and outbound communication logs.",
    "author": "Sports Federation",
    "website": "",
    "license": "LGPL-3",
    "depends": [
        "sports_federation_base",
        "sports_federation_people",
        "sports_federation_tournament",
        "sports_federation_portal",
        "sports_federation_public_site",
        "sports_federation_result_control",
        "sports_federation_standings",
        "sports_federation_finance_bridge",
        "sports_federation_officiating",
        "mail",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/mail_templates.xml",
        "data/ir_cron.xml",
        "views/notification_log_views.xml",
        "views/menu_views.xml",
    ],
    "demo": [],
    "installable": True,
    "auto_install": False,
    "sequence": 35,
}
