{
    "name": "Sports Federation Base",
    "version": "19.0.1.1.0",
    "category": "Sports",
    "summary": "Base module for federation clubs, teams, seasons, and registrations",
    "author": "Sports Federation",
    "website": "",
    "license": "LGPL-3",
    "depends": ["base", "mail", "base_setup"],
    "data": [
        "security/res_groups.xml",
        "security/ir.model.access.csv",
        "data/ir_sequence.xml",
        "views/res_config_settings_views.xml",
        "views/federation_season_registration_views.xml",
        "views/federation_season_views.xml",
        "views/federation_team_views.xml",
        "views/federation_club_views.xml",
        "views/menu_items.xml",
    ],
    "demo": [],
    "installable": True,
    "application": True,
    "auto_install": False,
    "sequence": 10,
}
