{
    "name": "Sports Federation",
    "version": "19.0.1.0.0",
    "category": "Sports",
    "summary": "Complete sports federation platform",
    "description": """
Single supported installation entry point for the production federation
platform. Domain implementation remains in focused internal addons so existing
databases, model names, XML IDs, and upgrade paths stay stable.
""",
    "author": "Sports Federation",
    "website": "",
    "license": "LGPL-3",
    "depends": [
        "sports_federation_base",
        "sports_federation_people",
        "sports_federation_rules",
        "sports_federation_tournament",
        "sports_federation_venues",
        "sports_federation_competition_core",
        "sports_federation_registration",
        "sports_federation_result_control",
        "sports_federation_format",
        "sports_federation_calendar",
        "sports_federation_scheduling",
        "sports_federation_schedule_approval",
        "sports_federation_matchday",
        "sports_federation_officiating",
        "sports_federation_rosters",
        "sports_federation_standings",
        "sports_federation_compliance",
        "sports_federation_discipline",
        "sports_federation_governance",
        "sports_federation_finance_bridge",
        "sports_federation_notifications",
        "sports_federation_portal",
        "sports_federation_public_site",
        "sports_federation_reporting",
        "sports_federation_import_tools",
    ],
    "data": [],
    "demo": [],
    "installable": True,
    "application": True,
    "auto_install": False,
    "sequence": 1,
}
