{
    "name": "Sports Federation Import Tools",
    "version": "19.0.1.2.0",
    "category": "Sports",
    "summary": "Wizard-driven CSV import tools for clubs, seasons, teams, players, and tournament participants",
    "description": "CSV import wizards with dry-run validation, mapping guidance, and duplicate-safe onboarding for clubs, seasons, teams, players, and tournament participants.",
    "author": "Sports Federation",
    "website": "",
    "license": "LGPL-3",
    "depends": [
        "sports_federation_base",
        "sports_federation_people",
        "sports_federation_tournament",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/import_template_data.xml",
        "data/integration_contract_data.xml",
        "data/integration_retention_cron.xml",
        "views/import_governance_views.xml",
        "views/integration_partner_views.xml",
        "views/import_wizard_views.xml",
        "views/menu_views.xml",
    ],
    "demo": [],
    "installable": True,
    "auto_install": False,
    "sequence": 60,
}
