IMPORT_JOB_STATE_DRAFT = "draft"
IMPORT_JOB_STATE_AWAITING_APPROVAL = "awaiting_approval"
IMPORT_JOB_STATE_APPROVED = "approved"
IMPORT_JOB_STATE_COMPLETED = "completed"
IMPORT_JOB_STATE_COMPLETED_WITH_ERRORS = "completed_with_errors"
IMPORT_JOB_STATE_REJECTED = "rejected"

IMPORT_JOB_STATE_SELECTION = [
    (IMPORT_JOB_STATE_DRAFT, "Draft"),
    (IMPORT_JOB_STATE_AWAITING_APPROVAL, "Awaiting Approval"),
    (IMPORT_JOB_STATE_APPROVED, "Approved"),
    (IMPORT_JOB_STATE_COMPLETED, "Completed"),
    (IMPORT_JOB_STATE_COMPLETED_WITH_ERRORS, "Completed With Errors"),
    (IMPORT_JOB_STATE_REJECTED, "Rejected"),
]

IMPORT_JOB_RESUBMITTABLE_STATES = (
    IMPORT_JOB_STATE_DRAFT,
    IMPORT_JOB_STATE_REJECTED,
)
IMPORT_JOB_REJECTABLE_STATES = (
    IMPORT_JOB_STATE_AWAITING_APPROVAL,
    IMPORT_JOB_STATE_APPROVED,
)
IMPORT_JOB_ERROR_STATES = (
    IMPORT_JOB_STATE_COMPLETED_WITH_ERRORS,
    IMPORT_JOB_STATE_REJECTED,
)

INBOUND_DELIVERY_STATE_STAGED = "staged"
INBOUND_DELIVERY_STATE_PREVIEWED = "previewed"
INBOUND_DELIVERY_STATE_AWAITING_APPROVAL = "awaiting_approval"
INBOUND_DELIVERY_STATE_APPROVED = "approved"
INBOUND_DELIVERY_STATE_PROCESSED = "processed"
INBOUND_DELIVERY_STATE_PROCESSED_WITH_ERRORS = "processed_with_errors"
INBOUND_DELIVERY_STATE_FAILED = "failed"
INBOUND_DELIVERY_STATE_CANCELLED = "cancelled"

INBOUND_DELIVERY_STATE_SELECTION = [
    (INBOUND_DELIVERY_STATE_STAGED, "Staged"),
    (INBOUND_DELIVERY_STATE_PREVIEWED, "Previewed"),
    (INBOUND_DELIVERY_STATE_AWAITING_APPROVAL, "Awaiting Approval"),
    (INBOUND_DELIVERY_STATE_APPROVED, "Approved"),
    (INBOUND_DELIVERY_STATE_PROCESSED, "Processed"),
    (INBOUND_DELIVERY_STATE_PROCESSED_WITH_ERRORS, "Processed With Errors"),
    (INBOUND_DELIVERY_STATE_FAILED, "Failed"),
    (INBOUND_DELIVERY_STATE_CANCELLED, "Cancelled"),
]

INBOUND_DELIVERY_ACTIVE_STATES = (
    INBOUND_DELIVERY_STATE_STAGED,
    INBOUND_DELIVERY_STATE_PREVIEWED,
    INBOUND_DELIVERY_STATE_AWAITING_APPROVAL,
    INBOUND_DELIVERY_STATE_APPROVED,
)
INBOUND_DELIVERY_PROCESSED_STATES = (
    INBOUND_DELIVERY_STATE_PROCESSED,
    INBOUND_DELIVERY_STATE_PROCESSED_WITH_ERRORS,
)
INBOUND_DELIVERY_FAILURE_REVIEW_STATES = (
    INBOUND_DELIVERY_STATE_PREVIEWED,
    INBOUND_DELIVERY_STATE_PROCESSED_WITH_ERRORS,
    INBOUND_DELIVERY_STATE_FAILED,
)


def is_import_job_approved(state):
    """Return whether the governance job is in the approved execution state."""
    return state == IMPORT_JOB_STATE_APPROVED


def is_import_job_rejected(state):
    """Return whether the governance job is in the rejected terminal state."""
    return state == IMPORT_JOB_STATE_REJECTED


def delivery_state_from_job_state(job_state):
    """Map governance completion states onto the linked inbound delivery state."""
    if job_state == IMPORT_JOB_STATE_COMPLETED:
        return INBOUND_DELIVERY_STATE_PROCESSED
    return INBOUND_DELIVERY_STATE_PROCESSED_WITH_ERRORS


def delivery_uses_validation_feedback(state):
    """Return whether a delivery state should default to validation-style feedback."""
    return state in (
        INBOUND_DELIVERY_STATE_PREVIEWED,
        INBOUND_DELIVERY_STATE_PROCESSED_WITH_ERRORS,
    )
