{
    "name": "Sports Federation Reporting",
    "version": "19.0.1.2.0",
    "category": "Sports",
    "summary": "Reporting models for federation data",
    "description": "Reporting models and dashboards for participation, officiating, compliance, and finance.",
    "author": "Sports Federation",
    "website": "",
    "license": "LGPL-3",
    "depends": [
        "web",
        "sports_federation_base",
        "sports_federation_people",
        "sports_federation_tournament",
        "sports_federation_officiating",
        "sports_federation_standings",
        "sports_federation_discipline",
        "sports_federation_compliance",
        "sports_federation_finance_bridge",
        "sports_federation_notifications",
        "sports_federation_result_control",
        "sports_federation_governance",
        "sports_federation_import_tools",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/report_schedule_cron.xml",
        "data/report_snapshot_cron.xml",
        "views/report_participation_views.xml",
        "views/report_officiating_views.xml",
        "views/report_compliance_views.xml",
        "views/report_finance_views.xml",
        "views/report_operational_views.xml",
        "views/report_operator_checklist_views.xml",
        "views/report_planning_views.xml",
        "views/report_audit_event_views.xml",
        "views/report_snapshot_views.xml",
        "views/report_schedule_views.xml",
        "views/menu_views.xml",
    ],
    "demo": [],
    "installable": True,
    "auto_install": False,
    "sequence": 75,
}
