from . import test_http_smoke
from . import test_public_site
from . import test_public_api
from . import test_template_accessibility
from . import test_tour_publication
from . import test_club_team_pages
from . import test_player_pages
from . import test_club_team_pages
from . import test_player_pages
