{
    "name": "Competition Scheduling",
    "version": "19.0.3.1.0",
    "category": "Sports",
    "summary": "Working schedules, assignments, validation and deterministic proposals",
    "author": "Sports Federation",
    "license": "LGPL-3",
    "depends": ["sports_federation_calendar"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "views/scheduling_views.xml",
        "views/submit_schedule_wizard_views.xml",
        "views/fairness_views.xml",
        "views/menu.xml",
    ],
    "installable": True,
    "application": False,
    "auto_install": False,
}
