{
    "name": "Sports Federation Rules",
    "version": "19.0.1.1.0",
    "category": "Sports",
    "summary": "Competition definitions, rule sets, scoring, tie-break, eligibility, and qualification configuration",
    "author": "Dodgeball Belgium: Cedric Bouckaert",
    "website": "",
    "license": "LGPL-3",
    "depends": ["sports_federation_base"],
    "data": [
        "security/ir.model.access.csv",
        "views/federation_rule_set_views.xml",
        "views/federation_points_rule_views.xml",
        "views/federation_tie_break_rule_views.xml",
        "views/federation_eligibility_rule_views.xml",
        "views/federation_qualification_rule_views.xml",
        "views/menu_items.xml",
    ],
    "demo": [],
    "installable": True,
    "application": False,
    "auto_install": False,
    "sequence": 15,
}
