from . import federation_competition
from . import federation_competition_edition
from . import federation_tournament
from . import federation_tournament_stage
from . import federation_tournament_group
from . import federation_tournament_round
from . import federation_tournament_participant
from . import federation_match
from . import federation_match_bracket
from . import federation_season_registration_inherit
from . import federation_season_inherit
