#!/usr/bin/env python3
"""Static checks for the complete repository checkout."""

import ast
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
errors = []
python_count = xml_count = manifest_count = 0

for module in sorted(ROOT.glob("sports_federation_*")):
    if not module.is_dir():
        continue
    for path in module.rglob("*.py"):
        if "__pycache__" in path.parts:
            continue
        python_count += 1
        try:
            ast.parse(path.read_text(encoding="utf-8"))
        except Exception as exc:
            errors.append(f"Python: {path.relative_to(ROOT)}: {exc}")
    for path in module.rglob("*.xml"):
        xml_count += 1
        try:
            ET.parse(path)
        except Exception as exc:
            errors.append(f"XML: {path.relative_to(ROOT)}: {exc}")
    manifest = module / "__manifest__.py"
    if manifest.exists():
        manifest_count += 1
        try:
            values = ast.literal_eval(manifest.read_text(encoding="utf-8"))
            for relative in values.get("data", []) + values.get("demo", []):
                if not (module / relative).exists():
                    errors.append(f"Manifest: {module.name}/{relative} is missing")
        except Exception as exc:
            errors.append(f"Manifest: {manifest.relative_to(ROOT)}: {exc}")

for generated in ROOT.rglob("*.pyc"):
    errors.append(f"Generated bytecode committed: {generated.relative_to(ROOT)}")
for cache in ROOT.rglob("__pycache__"):
    errors.append(f"Generated cache committed: {cache.relative_to(ROOT)}")

print(
    f"Checked {python_count} Python files, {xml_count} XML files, and {manifest_count} manifests."
)
for error in errors:
    print(error, file=sys.stderr)
sys.exit(1 if errors else 0)
