{
    "name": "Sports Federation Club Roles & Portal",
    "version": "19.0.1.3.0",
    "category": "Sports",
    "summary": "Club contacts, representative roles, portal website and registration flows",
    "description": """
Portal and website flows for sports federation club representatives.

Provides club representative ownership, portal dashboards, season and
tournament registration workflows, and the live tournament operations board
on top of the federation base modules.
""",
    "author": "Sports Federation",
    "website": "",
    "license": "LGPL-3",
    "depends": [
        "website",
        "portal",
        "sports_federation_base",
        "sports_federation_people",
        "sports_federation_tournament",
        "sports_federation_officiating",
        "sports_federation_rosters",
        "sports_federation_result_control",
    ],
    "data": [
        "security/res_groups.xml",
        "security/ir.model.access.csv",
        "security/ir_rule.xml",
        "data/federation_club_role_type.xml",
        "data/ir_sequence.xml",
        "views/federation_club_role_type_views.xml",
        "views/federation_club_representative_views.xml",
        "views/federation_club_views.xml",
        "views/federation_referee_views.xml",
        "views/res_partner_views.xml",
        "views/res_users_views.xml",
        "views/federation_season_registration_views.xml",
        "views/federation_tournament_registration_views.xml",
        "views/federation_tournament_views.xml",
        "views/federation_match_sheet_views.xml",
        "views/federation_club_representative_portal_views.xml",
        "views/portal_templates.xml",
        "views/portal_officiating_templates.xml",
        "views/portal_tournament_workspace_templates.xml",
        "views/portal_tournament_operations_templates.xml",
        "views/portal_roster_templates.xml",
        "views/portal_result_templates.xml",
        "views/portal_referee_duty_templates.xml",
        "views/menu_items.xml",
        "views/website_menus.xml",
    ],
    "assets": {
        "web.assets_frontend": [
            "sports_federation_portal/static/src/components/tournament_operations/tournament_operations.js",
            "sports_federation_portal/static/src/components/tournament_operations/tournament_operations.xml",
            "sports_federation_portal/static/src/components/tournament_operations/tournament_operations.scss",
        ],
    },
    "demo": [],
    "installable": True,
    "application": False,
    "auto_install": False,
    "sequence": 15,
}
