{
    "name": "Sports Federation Competition Engine",
    "version": "19.0.1.0.0",
    "category": "Sports",
    "summary": "Competition engine with round-robin and knockout generation wizards",
    "description": "Competition generation services and wizards for round-robin and knockout tournaments.",
    "author": "Sports Federation",
    "website": "",
    "license": "LGPL-3",
    "depends": ["sports_federation_tournament", "sports_federation_standings"],
    "data": [
        "security/ir.model.access.csv",
        "views/stage_progression_views.xml",
        "views/tournament_template_views.xml",
        "wizards/round_robin_wizard_views.xml",
        "wizards/knockout_wizard_views.xml",
        "wizards/round_date_wizard_views.xml",
        "views/tournament_buttons.xml",
    ],
    "demo": [],
    "installable": True,
    "auto_install": False,
    "sequence": 30,
}
