{
    "name": "Sports Federation Competition Engine",
    "version": "19.0.1.2.0",
    "category": "Sports",
    "summary": "Competition engine with round-robin and knockout generation wizards",
    "description": "Competition generation services and wizards for round-robin and knockout tournaments.",
    "author": "Sports Federation",
    "website": "",
    "license": "LGPL-3",
    "depends": [
        "web",
        "sports_federation_tournament",
        "sports_federation_standings",
        "sports_federation_venues",
    ],
    "data": [
        "security/competition_workspace_security.xml",
        "security/ir.model.access.csv",
        "views/stage_progression_views.xml",
        "views/competition_workspace_views.xml",
        "views/tournament_template_views.xml",
        "wizards/round_robin_wizard_views.xml",
        "wizards/knockout_wizard_views.xml",
        "wizards/round_date_wizard_views.xml",
        "views/tournament_buttons.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "sports_federation_competition_engine/static/src/client_actions/competition_workspace/competition_workspace.js",
            "sports_federation_competition_engine/static/src/client_actions/competition_workspace/competition_workspace.xml",
            "sports_federation_competition_engine/static/src/client_actions/competition_workspace/competition_workspace.scss",
        ],
        "web.qunit_suite_tests": [
            "sports_federation_competition_engine/static/tests/competition_workspace_ui_tests.js",
        ],
    },
    "demo": [],
    "installable": True,
    "auto_install": False,
    "sequence": 30,
}
