{
    "name": "Sports Federation Public Site",
    "version": "19.0.1.2.0",
    "category": "Sports",
    "summary": "Public tournament coverage integrated into the website tournament hub",
    "description": "Public website pages for tournament coverage, standings, results, schedules, and federation events.",
    "author": "Sports Federation",
    "website": "",
    "license": "LGPL-3",
    "depends": [
        "website",
        "portal",
        "sports_federation_tournament",
        "sports_federation_standings",
        "sports_federation_venues",
        "sports_federation_result_control",
        "sports_federation_people",
    ],
    "data": [
        "security/ir.model.access.csv",
        "views/website_templates.xml",
        "views/website_hub_templates.xml",
        "views/website_editorial_templates.xml",
        "views/website_clubs_players_templates.xml",
        "views/website_menu.xml",
        "views/season_views_inherit.xml",
        "views/tournament_views_inherit.xml",
        "views/team_views_inherit.xml",
        "views/standing_views_inherit.xml",
        "views/editorial_views.xml",
    ],
    "demo": [],
    "post_init_hook": "post_init_hook",
    "installable": True,
    "auto_install": False,
    "sequence": 70,
}
