{
    "name": "Sports Federation Public Site",
    "version": "19.0.2.0.0",
    "category": "Sports",
    "summary": "Public competition, match-day, standings and bracket experience",
    "description": "Public website pages for tournament coverage, standings, results, schedules, and federation events.",
    "author": "Sports Federation",
    "website": "",
    "license": "LGPL-3",
    "depends": [
        "website",
        "portal",
        "sports_federation_base",
        "sports_federation_tournament",
        "sports_federation_standings",
        "sports_federation_venues",
        "sports_federation_result_control",
        "sports_federation_people",
        "sports_federation_competition_core",
        "sports_federation_format",
        "sports_federation_calendar",
        "sports_federation_schedule_approval",
        "sports_federation_matchday",
    ],
    "data": [
        "security/ir.model.access.csv",
        "views/website_templates.xml",
        "views/website_competition_templates.xml",
        "views/competition_edition_views_inherit.xml",
        "views/website_hub_templates.xml",
        "views/website_editorial_templates.xml",
        "views/website_clubs_players_templates.xml",
        "views/website_menu.xml",
        "views/season_views_inherit.xml",
        "views/tournament_views_inherit.xml",
        "views/team_views_inherit.xml",
        "views/standing_views_inherit.xml",
        "views/editorial_views.xml",
    ],
    "assets": {
        "web.assets_frontend": [
            "sports_federation_public_site/static/src/scss/public_competitions_current.scss",
            "sports_federation_public_site/static/src/js/public_live_board.js",
        ],
    },
    "demo": [],
    "post_init_hook": "post_init_hook",
    "installable": True,
    "auto_install": False,
    "sequence": 70,
}
